Org users can see **all** other users in org
Affects `GET /v3/users`

Much of this code is simplification: previously we had a much more
granular permissions structure (e.g. a user in a space in an org could
not see users outside its space). Now visibility is determined at the
org level (every user assigned a space role will also have an org role).

Exception: a user could always see themselves even if they weren't a
member of any org.

We removed `visible_users_in_my_spaces`; it no longer had a purpose.

We formatted the code to be more readable.

[#168117402]

Co-authored-by: Belinda Liu <bliu@pivotal.io>
Co-authored-by: Brian Cunnie <bcunnie@pivotal.io>